# Links on sidebar
menu:
  Home: /
  Categories: /categories/
  Archive: /archives/
  Tags: /tags/
  About: /about/

# Pictures shown on the sidebar
# Use the absolute URL after generating
avatar: /assets/m_avt.png
sidebar_background: /assets/black_pattern.jpg

rss: /atom.xml

# Content
excerpt_link: Read On Â»

# Will be shown on the bottom.
## To add new icon, just copy .svg to source/assets/ and add entries below.
media:
  # github: https://github.com/nameoverflow
  # facebook: https://www.facebook.com/profile.php?id=100004252391322

source_han_font: true

# Disqus settings
disqus:
  # 'disabled' | 'all' | 'post'
  enable: disabled
  # Shortname of your disqus website.
  # See disqus admin
  shortname:

# Math
mathEngine: 'katex' # or 'katex 'mathjax''
math:
  enable: true
  all_pages: true
  mathjax:
    src: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    # config: {
    #   tex2jax: {
    #     inlineMath: [ ['$','$'], ["\\(","\\)"] ],
    #     skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code'],
    #     processEscapes: true
    #   },
    #   TeX: {
    #     equationNumbers: {
    #       autoNumber: "AMS"
    #     }
    #   }
    # }
  katex:
    src:
      css: https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.css
      js: https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.js
      autorender: https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/contrib/auto-render.min.js

# Miscellaneous
favicon:
